import { LinearGradient } from "expo-linear-gradient";
import { router } from "expo-router";
import React from "react";
import {
  Linking,
  Platform,
  ScrollView,
  StatusBar,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from "react-native";

import Feather from "@expo/vector-icons/Feather";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";

interface PrivacyPart {
  title: string;
  content: Content[];
}

interface Content {
  subtitle: string;
  text?: string;
  subsections?: Subsection[];
  list?: string[];
}

interface Subsection {
  title: string;
  text: string;
  list?: string[];
}

export default function PrivacyPolicyScreen() {
  const sections: PrivacyPart[] = [
    {
      title: "Interpretation and Definitions",
      content: [
        {
          subtitle: "Interpretation",
          text: "The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.",
        },
        {
          subtitle: "Definitions",
          text: "For the purposes of this Privacy Policy:",
          list: [
            "Account means a unique account created for You to access our Service or parts of our Service.",
            'Affiliate means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.',
            "Application refers to Chatbot Cecy, the software program provided by the Company.",
            'Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Colegio de Estudios Científicos y Tecnológicos del Estado de Michoacán, Loma de las Liebres 180, 58095.',
            "Country refers to: Mexico",
            "Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.",
            "Personal Data is any information that relates to an identified or identifiable individual.",
            "Service refers to the Application.",
            "Service Provider means any natural or legal person who processes the data on behalf of the Company.",
            "Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.",
            "You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.",
          ],
        },
      ],
    },
    {
      title: "Collecting and Using Your Personal Data",
      content: [
        {
          subtitle: "Types of Data Collected",
          subsections: [
            {
              title: "Personal Data",
              text: "While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:",
              list: ["Usage Data"],
            },
            {
              title: "Usage Data",
              text: "Usage Data is collected automatically when using the Service.\n\nUsage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.\n\nWhen You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.",
            },
          ],
        },
        {
          subtitle: "Use of Your Personal Data",
          text: "The Company may use Personal Data for the following purposes:",
          list: [
            "To provide and maintain our Service, including to monitor the usage of our Service.",
            "To manage Your Account: to manage Your registration as a user of the Service.",
            "For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased.",
            "To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication.",
            "To provide You with news, special offers and general information about other goods, services and events.",
            "To manage Your requests: To attend and manage Your requests to Us.",
            "For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets.",
            "For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns.",
          ],
        },
      ],
    },
    {
      title: "Data Sharing and Retention",
      content: [
        {
          subtitle: "Retention of Your Personal Data",
          text: "The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.",
        },
        {
          subtitle: "Transfer of Your Personal Data",
          text: "Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.",
        },
        {
          subtitle: "Delete Your Personal Data",
          text: "You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You. Our Service may give You the ability to delete certain information about You from within the Service.",
        },
      ],
    },
    {
      title: "Security and Legal Requirements",
      content: [
        {
          subtitle: "Security of Your Personal Data",
          text: "The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.",
        },
        {
          subtitle: "Disclosure of Your Personal Data",
          text: "The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:",
          list: [
            "Comply with a legal obligation",
            "Protect and defend the rights or property of the Company",
            "Prevent or investigate possible wrongdoing in connection with the Service",
            "Protect the personal safety of Users of the Service or the public",
            "Protect against legal liability",
          ],
        },
      ],
    },
    {
      title: "Additional Information",
      content: [
        {
          subtitle: "Children's Privacy",
          text: "Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us.",
        },
        {
          subtitle: "Links to Other Websites",
          text: "Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.",
        },
        {
          subtitle: "Changes to this Privacy Policy",
          text: "We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page. Changes to this Privacy Policy are effective when they are posted on this page.",
        },
      ],
    },
  ];

  async function navigateToCecytem() {
    await Linking.openURL("https://www.cecyteorienta.com/");
  }
  return (
    <View style={styles.container}>
      <StatusBar
        barStyle="light-content"
        backgroundColor="transparent"
        translucent={true}
      />

      <LinearGradient colors={["#45AAE3", "#53AB32"]} style={styles.header}>
        <View style={styles.headerContent}>
          <TouchableOpacity
            style={styles.backButton}
            onPress={() => router.back()}
          >
            <Feather name="arrow-left" size={24} color="#FFFFFF" />
          </TouchableOpacity>
          <View style={styles.headerTextContainer}>
            <Text style={styles.headerTitle}>Política de Privacidad</Text>
            <Text style={styles.headerSubtitle}>
              Última actualización: 30 de junio, 2025
            </Text>
          </View>
        </View>
      </LinearGradient>

      <ScrollView
        style={styles.content}
        contentContainerStyle={styles.contentContainer}
        showsVerticalScrollIndicator={false}
      >
        {/* Introduction */}
        <View style={styles.introSection}>
          <View style={styles.introCard}>
            <MaterialIcons name="security" size={48} color="#45AAE3" />
            <Text style={styles.introTitle}>Tu Privacidad es Importante</Text>
            <Text style={styles.introText}>
              Esta Política de Privacidad describe nuestras políticas y
              procedimientos sobre la recopilación, uso y divulgación de tu
              información cuando usas el Servicio y te informa sobre tus
              derechos de privacidad y cómo la ley te protege.
            </Text>
          </View>
        </View>

        {/* Main Content Sections */}
        {sections.map((section, sectionIndex) => (
          <View key={sectionIndex} style={styles.section}>
            <Text style={styles.sectionTitle}>{section.title}</Text>

            {section.content.map((content, contentIndex) => (
              <View key={contentIndex} style={styles.contentBlock}>
                {content.subtitle && (
                  <Text style={styles.subtitle}>{content.subtitle}</Text>
                )}

                {content.text && (
                  <Text style={styles.bodyText}>{content.text}</Text>
                )}

                {content.list && (
                  <View style={styles.listContainer}>
                    {content.list.map((item, itemIndex) => (
                      <View key={itemIndex} style={styles.listItem}>
                        <View style={styles.bullet} />
                        <Text style={styles.listText}>{item}</Text>
                      </View>
                    ))}
                  </View>
                )}

                {content.subsections &&
                  content.subsections.map((subsection, subIndex) => (
                    <View key={subIndex} style={styles.subsection}>
                      <Text style={styles.subsectionTitle}>
                        {subsection.title}
                      </Text>
                      <Text style={styles.bodyText}>{subsection.text}</Text>
                      {subsection.list && (
                        <View style={styles.listContainer}>
                          {subsection.list.map((item, itemIndex) => (
                            <View key={itemIndex} style={styles.listItem}>
                              <View style={styles.bullet} />
                              <Text style={styles.listText}>{item}</Text>
                            </View>
                          ))}
                        </View>
                      )}
                    </View>
                  ))}
              </View>
            ))}
          </View>
        ))}

        {/* Contact Section */}
        <View style={styles.contactSection}>
          <View style={styles.contactCard}>
            <MaterialIcons name="contact-support" size={32} color="#53AB32" />
            <Text style={styles.contactTitle}>¿Tienes Preguntas?</Text>
            <Text style={styles.contactText}>
              Si tienes alguna pregunta sobre esta Política de Privacidad,
              puedes contactarnos visitando nuestro sitio web.
            </Text>
            <TouchableOpacity
              style={styles.contactButton}
              onPress={navigateToCecytem}
            >
              <Feather name="external-link" size={18} color="#FFFFFF" />
              <Text style={styles.contactButtonText}>Visitar Sitio Web</Text>
            </TouchableOpacity>
          </View>
        </View>
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F8FAFC",
  },
  header: {
    paddingHorizontal: 20,
    marginTop: Platform.OS == "android" ? 0 : 0,
    paddingTop:
      Platform.OS == "android" ? (StatusBar.currentHeight ?? 30) + 10 : 50,
    paddingBottom: 15,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
  },
  headerContent: {
    flexDirection: "row",
    alignItems: "center",
  },
  backButton: {
    marginRight: 16,
    padding: 8,
  },
  headerTextContainer: {
    flex: 1,
  },
  headerTitle: {
    fontSize: 28,
    fontWeight: "700",
    color: "#FFFFFF",
    marginBottom: 4,
  },
  headerSubtitle: {
    fontSize: 14,
    color: "#E2E8F0",
    opacity: 0.9,
  },
  content: {
    flex: 1,
  },
  contentContainer: {
    padding: 20,
  },
  introSection: {
    marginBottom: 32,
  },
  introCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 24,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
  },
  introTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#1E293B",
    marginTop: 16,
    marginBottom: 12,
    textAlign: "center",
  },
  introText: {
    fontSize: 16,
    color: "#64748B",
    lineHeight: 24,
    textAlign: "center",
  },
  section: {
    marginBottom: 32,
  },
  sectionTitle: {
    fontSize: 22,
    fontWeight: "700",
    color: "#1E293B",
    marginBottom: 16,
  },
  contentBlock: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 3,
  },
  subtitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#1E293B",
    marginBottom: 12,
  },
  subsection: {
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: "#E2E8F0",
  },
  subsectionTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#475569",
    marginBottom: 8,
  },
  bodyText: {
    fontSize: 14,
    color: "#64748B",
    lineHeight: 22,
    marginBottom: 12,
  },
  listContainer: {
    marginTop: 8,
  },
  listItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 8,
  },
  bullet: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#45AAE3",
    marginTop: 8,
    marginRight: 12,
  },
  listText: {
    fontSize: 14,
    color: "#64748B",
    lineHeight: 20,
    flex: 1,
  },
  contactSection: {
    marginBottom: 20,
  },
  contactCard: {
    backgroundColor: "#F0FDF4",
    borderRadius: 20,
    padding: 24,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#BBF7D0",
  },
  contactTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#166534",
    marginTop: 12,
    marginBottom: 8,
  },
  contactText: {
    fontSize: 16,
    color: "#15803D",
    lineHeight: 24,
    textAlign: "center",
    marginBottom: 20,
  },
  contactButton: {
    backgroundColor: "#53AB32",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 12,
  },
  contactButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
    marginLeft: 8,
  },
});
